//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shot.Licensing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shot.Licensing.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.00.
        /// </summary>
        internal static string ACT00Code {
            get {
                return ResourceManager.GetString("ACT00Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you receive one of these activation errors with your business product..
        /// </summary>
        internal static string ACT00Message {
            get {
                return ResourceManager.GetString("ACT00Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email to Technical Support..
        /// </summary>
        internal static string ACT00Resolve {
            get {
                return ResourceManager.GetString("ACT00Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.1.
        /// </summary>
        internal static string ACT01Code {
            get {
                return ResourceManager.GetString("ACT01Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not reach the activation server..
        /// </summary>
        internal static string ACT01Message {
            get {
                return ResourceManager.GetString("ACT01Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if you have an active internet connection..
        /// </summary>
        internal static string ACT01Resolve {
            get {
                return ResourceManager.GetString("ACT01Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.2.
        /// </summary>
        internal static string ACT02Code {
            get {
                return ResourceManager.GetString("ACT02Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation failed..
        /// </summary>
        internal static string ACT02Message {
            get {
                return ResourceManager.GetString("ACT02Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your product is having trouble connecting with License servers..
        /// </summary>
        internal static string ACT02Resolve {
            get {
                return ResourceManager.GetString("ACT02Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.3.
        /// </summary>
        internal static string ACT03Code {
            get {
                return ResourceManager.GetString("ACT03Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation failed/Invalid License Key..
        /// </summary>
        internal static string ACT03Message {
            get {
                return ResourceManager.GetString("ACT03Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type or copy/paste the License Key into your product as it is written..
        /// </summary>
        internal static string ACT03Resolve {
            get {
                return ResourceManager.GetString("ACT03Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.4.
        /// </summary>
        internal static string ACT04Code {
            get {
                return ResourceManager.GetString("ACT04Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Failed - Canceled license..
        /// </summary>
        internal static string ACT04Message {
            get {
                return ResourceManager.GetString("ACT04Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify you are activating using the most recent License Key..
        /// </summary>
        internal static string ACT04Resolve {
            get {
                return ResourceManager.GetString("ACT04Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.5.
        /// </summary>
        internal static string ACT05Code {
            get {
                return ResourceManager.GetString("ACT05Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation key is used for a different product..
        /// </summary>
        internal static string ACT05Message {
            get {
                return ResourceManager.GetString("ACT05Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify you downloaded the correct product for the license you purchased..
        /// </summary>
        internal static string ACT05Resolve {
            get {
                return ResourceManager.GetString("ACT05Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.6.
        /// </summary>
        internal static string ACT06Code {
            get {
                return ResourceManager.GetString("ACT06Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation failed..
        /// </summary>
        internal static string ACT06Message {
            get {
                return ResourceManager.GetString("ACT06Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activation failed because the license is already activated..
        /// </summary>
        internal static string ACT06Resolve {
            get {
                return ResourceManager.GetString("ACT06Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.7.
        /// </summary>
        internal static string ACT07Code {
            get {
                return ResourceManager.GetString("ACT07Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation failed..
        /// </summary>
        internal static string ACT07Message {
            get {
                return ResourceManager.GetString("ACT07Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activation failed because the license you are trying to activate is already expired..
        /// </summary>
        internal static string ACT07Resolve {
            get {
                return ResourceManager.GetString("ACT07Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.8.
        /// </summary>
        internal static string ACT08Code {
            get {
                return ResourceManager.GetString("ACT08Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT08Message {
            get {
                return ResourceManager.GetString("ACT08Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT08Resolve {
            get {
                return ResourceManager.GetString("ACT08Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT09Code {
            get {
                return ResourceManager.GetString("ACT09Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT09Message {
            get {
                return ResourceManager.GetString("ACT09Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT09Resolve {
            get {
                return ResourceManager.GetString("ACT09Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT10Code {
            get {
                return ResourceManager.GetString("ACT10Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT10Message {
            get {
                return ResourceManager.GetString("ACT10Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT10Resolve {
            get {
                return ResourceManager.GetString("ACT10Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT11Code {
            get {
                return ResourceManager.GetString("ACT11Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT11Message {
            get {
                return ResourceManager.GetString("ACT11Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT11Resolve {
            get {
                return ResourceManager.GetString("ACT11Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT12Code {
            get {
                return ResourceManager.GetString("ACT12Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT12Message {
            get {
                return ResourceManager.GetString("ACT12Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT12Resolve {
            get {
                return ResourceManager.GetString("ACT12Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT13Code {
            get {
                return ResourceManager.GetString("ACT13Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT13Message {
            get {
                return ResourceManager.GetString("ACT13Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT13Resolve {
            get {
                return ResourceManager.GetString("ACT13Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT14Code {
            get {
                return ResourceManager.GetString("ACT14Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT14Message {
            get {
                return ResourceManager.GetString("ACT14Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT14Resolve {
            get {
                return ResourceManager.GetString("ACT14Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT15Code {
            get {
                return ResourceManager.GetString("ACT15Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT15Message {
            get {
                return ResourceManager.GetString("ACT15Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT15Resolve {
            get {
                return ResourceManager.GetString("ACT15Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT16Code {
            get {
                return ResourceManager.GetString("ACT16Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT16Message {
            get {
                return ResourceManager.GetString("ACT16Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT16Resolve {
            get {
                return ResourceManager.GetString("ACT16Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT17Code {
            get {
                return ResourceManager.GetString("ACT17Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT17Message {
            get {
                return ResourceManager.GetString("ACT17Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACT17Resolve {
            get {
                return ResourceManager.GetString("ACT17Resolve", resourceCulture);
            }
        }
    }
}
