//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shot.Licensing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shot.Licensing.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.00.
        /// </summary>
        internal static string ACT00Code {
            get {
                return ResourceManager.GetString("ACT00Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation failed..
        /// </summary>
        internal static string ACT00Message {
            get {
                return ResourceManager.GetString("ACT00Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your product is having trouble connecting with License servers..
        /// </summary>
        internal static string ACT00Resolve {
            get {
                return ResourceManager.GetString("ACT00Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.01.
        /// </summary>
        internal static string ACT01Code {
            get {
                return ResourceManager.GetString("ACT01Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation failed/Invalid License Key..
        /// </summary>
        internal static string ACT01Message {
            get {
                return ResourceManager.GetString("ACT01Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type or copy/paste the License Key into your product as it is written..
        /// </summary>
        internal static string ACT01Resolve {
            get {
                return ResourceManager.GetString("ACT01Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.02.
        /// </summary>
        internal static string ACT02Code {
            get {
                return ResourceManager.GetString("ACT02Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation key is used for a different product..
        /// </summary>
        internal static string ACT02Message {
            get {
                return ResourceManager.GetString("ACT02Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify you downloaded the correct product for the license you purchased..
        /// </summary>
        internal static string ACT02Resolve {
            get {
                return ResourceManager.GetString("ACT02Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.03.
        /// </summary>
        internal static string ACT03Code {
            get {
                return ResourceManager.GetString("ACT03Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Failed - Canceled license..
        /// </summary>
        internal static string ACT03Message {
            get {
                return ResourceManager.GetString("ACT03Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify you are activating using the most recent License Key..
        /// </summary>
        internal static string ACT03Resolve {
            get {
                return ResourceManager.GetString("ACT03Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.04.
        /// </summary>
        internal static string ACT04Code {
            get {
                return ResourceManager.GetString("ACT04Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation failed..
        /// </summary>
        internal static string ACT04Message {
            get {
                return ResourceManager.GetString("ACT04Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activation failed because the license you are trying to activate is already expired..
        /// </summary>
        internal static string ACT04Resolve {
            get {
                return ResourceManager.GetString("ACT04Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.05.
        /// </summary>
        internal static string ACT05Code {
            get {
                return ResourceManager.GetString("ACT05Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license is overused..
        /// </summary>
        internal static string ACT05Message {
            get {
                return ResourceManager.GetString("ACT05Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the license is no longer overused, attempt to activate again..
        /// </summary>
        internal static string ACT05Resolve {
            get {
                return ResourceManager.GetString("ACT05Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.06.
        /// </summary>
        internal static string ACT06Code {
            get {
                return ResourceManager.GetString("ACT06Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error..
        /// </summary>
        internal static string ACT06Message {
            get {
                return ResourceManager.GetString("ACT06Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are still unable to resolve your issue, email to Technical Support..
        /// </summary>
        internal static string ACT06Resolve {
            get {
                return ResourceManager.GetString("ACT06Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAL.00.
        /// </summary>
        internal static string VAL00Code {
            get {
                return ResourceManager.GetString("VAL00Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence file is missing..
        /// </summary>
        internal static string VAL00Message {
            get {
                return ResourceManager.GetString("VAL00Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to activate again..
        /// </summary>
        internal static string VAL00Resolve {
            get {
                return ResourceManager.GetString("VAL00Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAL.01.
        /// </summary>
        internal static string VAL01Code {
            get {
                return ResourceManager.GetString("VAL01Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed..
        /// </summary>
        internal static string VAL01Message {
            get {
                return ResourceManager.GetString("VAL01Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The licence file is invalid or corrupt..
        /// </summary>
        internal static string VAL01Resolve {
            get {
                return ResourceManager.GetString("VAL01Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAL.02.
        /// </summary>
        internal static string VAL02Code {
            get {
                return ResourceManager.GetString("VAL02Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License signature validation error..
        /// </summary>
        internal static string VAL02Message {
            get {
                return ResourceManager.GetString("VAL02Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license signature and data does not match. This usually happens when a license file is corrupted or has been altered..
        /// </summary>
        internal static string VAL02Resolve {
            get {
                return ResourceManager.GetString("VAL02Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAL.03.
        /// </summary>
        internal static string VAL03Code {
            get {
                return ResourceManager.GetString("VAL03Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensing for this product has expired..
        /// </summary>
        internal static string VAL03Message {
            get {
                return ResourceManager.GetString("VAL03Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license is expired. Please contact your distributor/vendor to renew the license..
        /// </summary>
        internal static string VAL03Resolve {
            get {
                return ResourceManager.GetString("VAL03Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAL.04.
        /// </summary>
        internal static string VAL04Code {
            get {
                return ResourceManager.GetString("VAL04Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license is not valid for current device..
        /// </summary>
        internal static string VAL04Message {
            get {
                return ResourceManager.GetString("VAL04Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please attempt to activate again..
        /// </summary>
        internal static string VAL04Resolve {
            get {
                return ResourceManager.GetString("VAL04Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAL.05.
        /// </summary>
        internal static string VAL05Code {
            get {
                return ResourceManager.GetString("VAL05Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License validation failed!.
        /// </summary>
        internal static string VAL05Message {
            get {
                return ResourceManager.GetString("VAL05Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are still unable to resolve your issue, email to Technical Support..
        /// </summary>
        internal static string VAL05Resolve {
            get {
                return ResourceManager.GetString("VAL05Resolve", resourceCulture);
            }
        }
    }
}
